# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIA', '0002_auto_20171107_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='township',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
